// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Banner.tsx";
import * as $$$$$$1 from "./sections/BigNumbers.tsx";
import * as $$$$$$2 from "./sections/Contact.tsx";
import * as $$$$$$3 from "./sections/Footer.tsx";
import * as $$$$$$4 from "./sections/Head.tsx";
import * as $$$$$$5 from "./sections/Header.tsx";
import * as $$$$$$6 from "./sections/HeroCompany.tsx";
import * as $$$$$$7 from "./sections/Image.tsx";
import * as $$$$$$8 from "./sections/Manifest.tsx";
import * as $$$$$$9 from "./sections/Testimony.tsx";
import * as $$$$$$10 from "./sections/Theme/Theme.tsx";
import * as $$$$$$11 from "./sections/TitleSection.tsx";

const manifest = {
  "sections": {
    "deco-sites/emvcfullsite/sections/Banner.tsx": $$$$$$0,
    "deco-sites/emvcfullsite/sections/BigNumbers.tsx": $$$$$$1,
    "deco-sites/emvcfullsite/sections/Contact.tsx": $$$$$$2,
    "deco-sites/emvcfullsite/sections/Footer.tsx": $$$$$$3,
    "deco-sites/emvcfullsite/sections/Head.tsx": $$$$$$4,
    "deco-sites/emvcfullsite/sections/Header.tsx": $$$$$$5,
    "deco-sites/emvcfullsite/sections/HeroCompany.tsx": $$$$$$6,
    "deco-sites/emvcfullsite/sections/Image.tsx": $$$$$$7,
    "deco-sites/emvcfullsite/sections/Manifest.tsx": $$$$$$8,
    "deco-sites/emvcfullsite/sections/Testimony.tsx": $$$$$$9,
    "deco-sites/emvcfullsite/sections/Theme/Theme.tsx": $$$$$$10,
    "deco-sites/emvcfullsite/sections/TitleSection.tsx": $$$$$$11,
  },
  "apps": {
    "deco-sites/emvcfullsite/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/emvcfullsite/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/emvcfullsite",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
